sudo: false
language: python
cache: pip
python:
- 2.7
- 3.4
- 3.5
- 3.6
- 3.7
  dist: xenial
env:
- DJANGO=1.8
- DJANGO=1.9
- DJANGO=1.10
- DJANGO=1.11
- DJANGO=2.0
- DJANGO=2.1
matrix:
  exclude:
  - python: 2.7
    env: DJANGO=2.0
  - python: 3.6
    env: DJANGO=1.8
  - python: 3.6
    env: DJANGO=1.9
  - python: 3.6
    env: DJANGO=1.10
  - python: 3.7
    env: DJANGO=1.8
  - python: 3.7
    env: DJANGO=1.9
  - python: 3.7
    env: DJANGO=1.10
  fast_finish: true
  include:
  - python: 3.6
    env: TOXENV=flake8
install: pip install tox-travis codecov
script: tox
after_success: coverage combine && codecov
branches:
  only:
  - master
  - /^v?\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
  provider: pypi
  user: jwilhelm
  password:
    secure: LzZk5DWafy6kZR//EH6iFsozmXVyAu86uuLKg0A82rLJBEV/ajLsbcLIk/G2FQdELs+s//6+v34r9PxeUbYE6xcb7hL+JF/dNotDnWG/AoCDD+xfHQqsIXUUnDbkTzm2a/d/QnC+3di6rnHzJlRSPX2wT2w6pHcQGbSE2bwOjHUe+apNWy7mImG9dF43nBEy16ihD2enEF+GVBe4SHl6eI9neqJWlHIUbMPG2LR/Nuo19AQCNfs9cFVwCNXWEhK+DY0PvMW/xnnYb/QxQcmgd9HtjC+I4ahj2Ggx0xkFaOjVmcIjFkxQj/ZQUxhYm0vJjrP43vSNUmzgfBdITnRvvJfS7bz+NZX9gx058XaazzyX7BWA/kSdJUq3DpoeTCaYzQrzi/DKgf0ox7jfQx9HvwMCSkel6Xf0K5YM3kylW/EhANbXDI4irtHUoU0BVQbXGKITgRtGbNL4zNUq60LwM7jpgFTVlzl+Fz5EAGqpVTuZtKiaPRNfYJorrQgtGG7ekFMDd1LP9UZ5hKTUAO7m5IPAcnUcLTT6BEXKbQSCz+kRj+F1nwZH6E4K90FKMaW/2opt2v5kyXsgli5ysrKmwfcXyhntxzr2eLTg75tMoJW1w5b7EJ7UY8b9JUAGiCVQCheFAIGaoL7UwBb0C1DHUm3l4nOaTlYwmaDOivT5jS8=
  on:
    tags: true
    python: 3.6
    condition: $TOXENV = flake8
    distributions: sdist bdist_wheel
    repo: godaddy/django-snow
