# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 00:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('sys_id', models.UUIDField(primary_key=True, serialize=False)),
                ('number', models.CharField(help_text='The Change Order number', max_length=32)),
                ('title', models.CharField(help_text='Title of the ServiceNow Change Request', max_length=160)),
                ('description', models.TextField(help_text='Description of the ServiceNow Change Request', validators=[django.core.validators.MaxLengthValidator(4000)])),
                ('assignment_group_guid', models.UUIDField()),
                ('state', models.CharField(choices=[('1', 'Open'), ('2', 'In Progress'), ('3', 'Complete'), ('4', 'Complete With Errors')], help_text='The current state the the change order is in.', max_length=1)),
            ],
            options={
                'verbose_name': 'service-now change request',
                'verbose_name_plural': 'service-now change requests',
            },
        ),
    ]
