# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_snow', '0001_initial'),
    ]

    # TODO state field must be altered to include the latest changes (once finalized).
    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='closed_time',
            field=models.DateTimeField(help_text='Timestamp when the Change Request was closed', null=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when the Change Request was created'),
            preserve_default=False,
        ),
    ]
