# Generated by Django 2.0.13 on 2019-06-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_snow', '0002_changemgmt_add_createtime_closetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='state',
            field=models.CharField(choices=[('1', 'Open'), ('2', 'In Progress'), ('3', 'Complete'), ('4', 'Complete With Errors')], help_text='The current state the change order is in.', max_length=3),
        ),
    ]
